name: ModernCrates
version: '${project.version}'
main: me.usainsrht.moderncrates.ModernCratesPlugin
api-version: '1.21'
folia-supported: true
description: Modern crate plugin for latest version Paper/Folia
authors:
  - UsainSrht
website: 'https://usainsrht.com'
dependencies:
  server:
    FancyHolograms:
      required: false
      join-classpath: true
    DecentHolograms:
      required: false
      join-classpath: true
    HolographicDisplays:
      required: false
      join-classpath: true